### PR TITLE
Create pl.json

### PR DESCRIPTION
**Pull request by nepozs**
Polish translation created (wind directions use international/english symbols).

### CODE REVIEW

**Comment by briis** [comment]
Thank you. Just to be sure, the Wind Directions in Polish are the same as for English?

**Comment by nepozs** [comment]
Yes, I'm pretty sure, that there is no polish equivalent for wind directions noted as shortcuts,

**Comment by briis** [comment]
Great, thanks for checking. I have merged it in, so it will be available on the next release.

**Comment by nepozs** [comment]
For future reference - polish long names:
https://pl.wikipedia.org/wiki/Rumb

**Comment by briis** [comment]
Thanks

**Pull request merged**
